
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 03 19:19:56 CST 2018
//----------------------------------------------------

package ANALIZADORES.LenguajeDracoScript;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 2;
  public static final int POT = 11;
  public static final int POR = 9;
  public static final int CHAR_LITERAL = 3;
  public static final int CPAR = 16;
  public static final int MAYQ = 25;
  public static final int CLLA = 18;
  public static final int FOR = 37;
  public static final int NOX = 34;
  public static final int NOT = 30;
  public static final int AND = 29;
  public static final int MENQ = 23;
  public static final int IGUAL = 21;
  public static final int APAR = 15;
  public static final int OR = 28;
  public static final int INC = 13;
  public static final int DIV = 10;
  public static final int ALLA = 17;
  public static final int IF = 32;
  public static final int OVAL = 42;
  public static final int ID = 6;
  public static final int QUADRATE = 41;
  public static final int PTO = 48;
  public static final int EOF = 0;
  public static final int ACORCH = 50;
  public static final int TRUE = 45;
  public static final int SMASH = 35;
  public static final int CCORCH = 51;
  public static final int error = 1;
  public static final int COMA = 49;
  public static final int NULO = 47;
  public static final int MENIQ = 24;
  public static final int LINE = 44;
  public static final int DIF = 27;
  public static final int MENOS = 8;
  public static final int MOD = 12;
  public static final int IG_IG = 22;
  public static final int MAYIQ = 26;
  public static final int NUM_LITERAL = 4;
  public static final int RUNMULTDASM = 39;
  public static final int POINT = 40;
  public static final int WHILE = 36;
  public static final int DECIMAL_LITERAL = 5;
  public static final int STRING = 43;
  public static final int DEC = 14;
  public static final int FALSE = 46;
  public static final int DSPTS = 20;
  public static final int VAR = 31;
  public static final int ELIF = 33;
  public static final int PRINT = 38;
  public static final int PYC = 19;
  public static final int MAS = 7;
}

