
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 22 19:09:13 CST 2018
//----------------------------------------------------

package ANALIZADORES.LenguajeD_PP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 2;
  public static final int POT = 11;
  public static final int ESTRUCT = 40;
  public static final int POR = 9;
  public static final int CHAR_LITERAL = 3;
  public static final int IMPRIMIR = 52;
  public static final int SI = 45;
  public static final int ENTERO = 35;
  public static final int CPAR = 15;
  public static final int MAYQ = 27;
  public static final int CLLA = 17;
  public static final int PRINCIPAL = 54;
  public static final int NOT = 32;
  public static final int AND = 31;
  public static final int MENQ = 25;
  public static final int IGUAL = 23;
  public static final int SINO = 46;
  public static final int CARACTER = 34;
  public static final int APAR = 14;
  public static final int OR = 30;
  public static final int MIENTRAS = 47;
  public static final int INC = 12;
  public static final int DIV = 10;
  public static final int ALLA = 16;
  public static final int CONTINUAR = 50;
  public static final int IMPORTAR = 42;
  public static final int ID = 6;
  public static final int SIGNO_Q = 44;
  public static final int PTO = 43;
  public static final int DECIMAL = 36;
  public static final int EOF = 0;
  public static final int CUADRADO = 56;
  public static final int ACORCH = 18;
  public static final int OVALO = 57;
  public static final int error = 1;
  public static final int CCORCH = 19;
  public static final int NULO = 41;
  public static final int COMA = 20;
  public static final int MENIQ = 26;
  public static final int CADENA = 33;
  public static final int DIF = 29;
  public static final int MENOS = 8;
  public static final int IG_IG = 24;
  public static final int MAYIQ = 28;
  public static final int NUM_LITERAL = 4;
  public static final int DETENER = 49;
  public static final int PUNTO = 55;
  public static final int VACIO = 53;
  public static final int FALSO = 38;
  public static final int DECIMAL_LITERAL = 5;
  public static final int BOOLEANO = 37;
  public static final int PARA = 48;
  public static final int RETORNAR = 51;
  public static final int VERDADERO = 39;
  public static final int DEC = 13;
  public static final int DSPTS = 22;
  public static final int LINEA = 58;
  public static final int PYC = 21;
  public static final int MAS = 7;
}

