
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 05 11:52:55 CST 2018
//----------------------------------------------------

package INTERPRETE_PILA.GRAMATICA;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 24;
  public static final int BR_IF = 27;
  public static final int FUNCTION = 16;
  public static final int SET_GLOBAL = 18;
  public static final int LTE = 10;
  public static final int POT = 6;
  public static final int MULT = 4;
  public static final int D_CHAR = 32;
  public static final int OUT_STR = 34;
  public static final int F_CHAR = 31;
  public static final int NOIGUAL = 36;
  public static final int MENORIGUAL = 38;
  public static final int NOT = 15;
  public static final int AND = 14;
  public static final int LT = 9;
  public static final int OR = 13;
  public static final int CALL = 33;
  public static final int DIV = 5;
  public static final int ID = 26;
  public static final int MAYORIGUAL = 40;
  public static final int EOF = 0;
  public static final int DECIMAL = 25;
  public static final int error = 1;
  public static final int GET_GLOBAL = 20;
  public static final int ADD = 2;
  public static final int MENOR = 37;
  public static final int MOD = 7;
  public static final int BR = 28;
  public static final int EQZ = 8;
  public static final int GTE = 12;
  public static final int MAYOR = 39;
  public static final int IGUALIGUAL = 35;
  public static final int GET_LOCAL = 19;
  public static final int END = 29;
  public static final int SET_LOCAL = 17;
  public static final int DIFF = 3;
  public static final int ETIQUETA = 23;
  public static final int GT = 11;
  public static final int R3T = 22;
  public static final int PRINT = 30;
  public static final int C4LC = 21;
}

